[phases.setup]
nixPkgs = ['php81', 'php81Extensions.pdo', 'php81Extensions.pdo_mysql', 'php81Extensions.mbstring', 'php81Extensions.xml', 'php81Extensions.curl', 'php81Extensions.gd', 'php81Extensions.zip', 'php81Extensions.imap']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader']

[phases.build]
cmds = ['php bin/console cache:clear --env=prod']

[start]
cmd = 'php -S 0.0.0.0:$PORT -t public'
